### ISSUE TITLE
jna invokation problem

### ISSUE THREAD

**Issue by colddew** [remram44/java-cpp-example#3]
https://github.com/remram44/java-cpp-example/blob/master/java-jna/java/src/edu/nyu/cpptest/cpplib/MyClass.java

```
[root@SzfyTestServer backup]# java -Djna.debug_load=true -classpath .:jna-5.5.0.jar MyClass
Feb 12, 2020 11:33:56 AM com.sun.jna.Native extractFromResourcePath
INFO: Looking in classpath from sun.misc.Launcher$AppClassLoader@4e0e2f2a for /com/sun/jna/linux-x86-64/libjnidispatch.so
Feb 12, 2020 11:33:56 AM com.sun.jna.Native extractFromResourcePath
INFO: Found library resource at jar:file:/opt/backup/jna-5.5.0.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Feb 12, 2020 11:33:56 AM com.sun.jna.Native extractFromResourcePath
INFO: Extracting library to /root/.cache/JNA/temp/jna15688228076106253.tmp
Feb 12, 2020 11:33:56 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Looking for library '/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so'
Feb 12, 2020 11:33:56 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Adding paths from jna.library.path: null
Feb 12, 2020 11:33:56 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so
Feb 12, 2020 11:33:56 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Found library '/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so' at /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'MyClass': /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so: undefined symbol: MyClass
        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:594)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:570)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:556)
        at com.sun.jna.Library$Handler.invoke(Library.java:243)
        at com.sun.proxy.$Proxy0.MyClass(Unknown Source)
        at MyClass.<init>(MyClass.java:23)
        at MyClass.main(MyClass.java:35)
```

when i test this demo it throw the exception, i wonder if 「cpplib_shared」 is casual, or can i use another name?

the second problem is if 「MyClass_」prefix is necessary?

**Comment by remram44** [comment]
For JNA, the name of the lib and the functions can be changed, so long as it matches.

**Comment by remram44** [comment]
Your error message says it can't find the function `MyClass`, however there is no such function. I also just tried this with the current JNA (`jna-5.5.0.jar`) and it worked for me. Did you make changes to the code?

**Comment by colddew** [comment]
https://github.com/remram44/java-cpp-example/tree/master/cpplib

i use these c++ code to generate libcpplib.so, but when i use jna to invoke libcpplib.so, it can load libcpplib.so, but can not find the method name. also `nm -D libcpplib.so`  show the method name are random strings

![image](https://user-images.githubusercontent.com/6032545/74352059-f10ff280-4df2-11ea-9654-2fb8a3d8176b.png)

can you give me some advice, thx

**Comment by colddew** [comment]
`java -Djna.debug_load=true -classpath .:jna-5.5.0.jar MyClass`

i use this script, jna version is newest

**Comment by remram44** [comment]
Those are the C++ functions, which do get mangled. That is why I use a tiny wrapper ([c_wrapper.cpp](https://github.com/remram44/java-cpp-example/blob/master/java-jna/c/c_wrapper.cpp)) with `extern "C"` functions which don't get mangled, and are the ones that get called from the [Java wrapper class](https://github.com/remram44/java-cpp-example/blob/master/java-jna/java/src/edu/nyu/cpptest/cpplib/MyClass.java).

![nm screenshot](https://user-images.githubusercontent.com/426784/74355188-84610d80-4d8a-11ea-9486-437ac33a23d3.png)

The alternative is to use Swig, which generates both wrapper for you.

**Comment by colddew** [comment]
```java
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;

public class MyClass {

    public interface CLibrary extends Library {

//        CLibrary INSTANCE = (CLibrary) Native.loadLibrary("cpplib_shared", CLibrary.class);
//        CLibrary INSTANCE = (CLibrary) Native.loadLibrary("cpplib", CLibrary.class);
        CLibrary INSTANCE = (CLibrary) Native.loadLibrary("/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so", CLibrary.class);

        Pointer MyClass_MyClass(int nb);

        int MyClass_getValue(Pointer self);

        void MyClass_increment(Pointer self);
    }

    private Pointer self;

    public MyClass(int nb) {
        self = CLibrary.INSTANCE.MyClass_MyClass(nb);
    }

    public int getValue() {
        return CLibrary.INSTANCE.MyClass_getValue(self);
    }

    public void increment() {
        CLibrary.INSTANCE.MyClass_increment(self);
    }

    public static void main(String[] args) {
        MyClass counter = new MyClass(3);
        counter.increment();
        counter.increment();
        System.out.println(counter.getValue());
    }
}
```

this is my java code

**Comment by colddew** [comment]
c++ code 

# https://github.com/remram44/java-cpp-example/blob/master/cpplib/include/cpplib/MyClass.h

```c++

#ifndef MYCLASS_H
#define MYCLASS_H

class MyClass {

private:
    int m_nb;

public:
    MyClass(int nb);
    int getValue() const;
    void increment();

};

#endif
```

# https://github.com/remram44/java-cpp-example/blob/master/cpplib/src/MyClass.cpp

```c++
#include "cpplib/MyClass.h"

MyClass::MyClass(int nb)
  : m_nb(nb)
{
}

int MyClass::getValue() const
{
    return m_nb;
}

void MyClass::increment()
{
    m_nb++;
}

```
function MyClass exist

**Comment by remram44** [comment]
You need a wrapper, you can only call `extern "C"` functions, not classes or methods

**Comment by colddew** [comment]
i am not familiar with c++, and i change code like this and re-make, but i has the same error

```
extern "C"
{
#include "cpplib/MyClass.h"

MyClass::MyClass(int nb)
  : m_nb(nb)
{
}

int MyClass::getValue() const
{
    return m_nb;
}

void MyClass::increment()
{
    m_nb++;
}
}
```

**Comment by colddew** [comment]
> Those are the C++ functions, which do get mangled. That is why I use a tiny wrapper ([c_wrapper.cpp](https://github.com/remram44/java-cpp-example/blob/master/java-jna/c/c_wrapper.cpp)) with `extern "C"` functions which don't get mangled, and are the ones that get called from the [Java wrapper class](https://github.com/remram44/java-cpp-example/blob/master/java-jna/java/src/edu/nyu/cpptest/cpplib/MyClass.java).
> 
> ![nm screenshot](https://user-images.githubusercontent.com/426784/74355188-84610d80-4d8a-11ea-9486-437ac33a23d3.png)
> 
> The alternative is to use Swig, which generates both wrapper for you.

ok, i get it, thank you very much

**Comment by colddew** [comment]
i replace MyClass.cpp with c_wrapper.cpp, and it throw another exception 「undefined symbol: _ZN7MyClassC1Ei」, how to solve this problem?


```
[root@SzfyTestServer build]# nm -D libcpplib.so 
0000000000201068 B __bss_start
                 w __cxa_finalize
0000000000201068 D _edata
0000000000201070 B _end
0000000000000a54 T _fini
                 w __gmon_start__
                 U __gxx_personality_v0
0000000000000818 T _init
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 w _Jv_RegisterClasses
00000000000009d0 T MyClass_ctor
0000000000000a1c T MyClass_getValue
0000000000000a36 T MyClass_increment
                 U _Unwind_Resume
                 U _ZdlPv
                 U _ZN7MyClass9incrementEv
                 U _ZN7MyClassC1Ei
                 U _ZNK7MyClass8getValueEv
                 U _Znwm
```

```
[root@SzfyTestServer backup]# java -Djna.debug_load=true -classpath .:jna-5.5.0.jar MyClass
Feb 13, 2020 1:23:01 AM com.sun.jna.Native extractFromResourcePath
INFO: Looking in classpath from sun.misc.Launcher$AppClassLoader@4e0e2f2a for /com/sun/jna/linux-x86-64/libjnidispatch.so
Feb 13, 2020 1:23:01 AM com.sun.jna.Native extractFromResourcePath
INFO: Found library resource at jar:file:/opt/backup/jna-5.5.0.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Feb 13, 2020 1:23:01 AM com.sun.jna.Native extractFromResourcePath
INFO: Extracting library to /root/.cache/JNA/temp/jna5644361781661826174.tmp
Feb 13, 2020 1:23:01 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Looking for library '/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so'
Feb 13, 2020 1:23:01 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Adding paths from jna.library.path: null
Feb 13, 2020 1:23:01 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so
Feb 13, 2020 1:23:01 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Found library '/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so' at /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so
java: symbol lookup error: /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so: undefined symbol: _ZN7MyClassC1Ei
```

**Comment by colddew** [comment]
i solve the problem, because i just compile c_wrapper.cpp and  forget to compile MyClass.cpp

now , it works

```
[root@SzfyTestServer backup]# java -Djna.debug_load=true -classpath .:jna-5.5.0.jar MyClass
Feb 13, 2020 1:23:01 AM com.sun.jna.Native extractFromResourcePath
INFO: Looking in classpath from sun.misc.Launcher$AppClassLoader@4e0e2f2a for /com/sun/jna/linux-x86-64/libjnidispatch.so
Feb 13, 2020 1:23:01 AM com.sun.jna.Native extractFromResourcePath
INFO: Found library resource at jar:file:/opt/backup/jna-5.5.0.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Feb 13, 2020 1:23:01 AM com.sun.jna.Native extractFromResourcePath
INFO: Extracting library to /root/.cache/JNA/temp/jna5644361781661826174.tmp
Feb 13, 2020 1:23:01 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Looking for library '/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so'
Feb 13, 2020 1:23:01 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Adding paths from jna.library.path: null
Feb 13, 2020 1:23:01 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so
Feb 13, 2020 1:23:01 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Found library '/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so' at /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so
java: symbol lookup error: /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so: undefined symbol: _ZN7MyClassC1Ei
[root@SzfyTestServer backup]# java -Djna.debug_load=true -classpath .:jna-5.5.0.jar MyClass
Feb 13, 2020 2:05:20 AM com.sun.jna.Native extractFromResourcePath
INFO: Looking in classpath from sun.misc.Launcher$AppClassLoader@4e0e2f2a for /com/sun/jna/linux-x86-64/libjnidispatch.so
Feb 13, 2020 2:05:20 AM com.sun.jna.Native extractFromResourcePath
INFO: Found library resource at jar:file:/opt/backup/jna-5.5.0.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Feb 13, 2020 2:05:20 AM com.sun.jna.Native extractFromResourcePath
INFO: Extracting library to /root/.cache/JNA/temp/jna1221045823503244492.tmp
Feb 13, 2020 2:05:20 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Looking for library '/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so'
Feb 13, 2020 2:05:20 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Adding paths from jna.library.path: null
Feb 13, 2020 2:05:20 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so
Feb 13, 2020 2:05:20 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Found library '/root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so' at /root/cpp_test/java-cpp-example-master/cpplib/build/libcpplib.so
5
```

**Comment by remram44** [comment]
Great, I'm glad I could help!
